# Generated by Django 2.2.10 on 2020-03-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_vendorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='brand',
            field=models.CharField(max_length=10, verbose_name='Brand Name'),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='info',
            field=models.CharField(max_length=255, verbose_name='Brand Info'),
        ),
    ]
