# Generated by Django 2.2.10 on 2020-02-28 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_cover',
            field=models.ImageField(blank=True, upload_to='product_covers/'),
        ),
    ]
