# Generated by Django 2.2.10 on 2020-03-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200310_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/covers/'),
        ),
    ]
