# Generated by Django 2.2.10 on 2020-03-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200310_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Nice', verbose_name='blank=True'),
            preserve_default=False,
        ),
    ]
