# Generated by Django 2.2.10 on 2020-03-14 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='category/covers/'),
        ),
    ]
