# Generated by Django 2.2.10 on 2020-03-14 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200314_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/covers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Product Description'),
        ),
    ]
